# Copy values into this file for local development.
# Example:
# mongodb_uri = "mongodb+srv://username:password@cluster.mongodb.net/"
# api_keys = { alpha_vantage = "", polygon = "" }

mongodb_uri = "mongodb+srv://nicholashansen42_db_user:8L58HUwyhhBr8trB@aieconapp.irs5nj2.mongodb.net/?appName=AIEconApp"
api_keys = {}
